services:
  vpn_bot:
    image: free_vpn_bot
    container_name: free_vpn_bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: python3 -m bot
    restart: always
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    env_file:
      - ".env"
    networks:
      - free_vpn_bot
networks:
  free_vpn_bot:
    driver: bridge
